{
 "title": "Toggl and Trello",
 "time": { "from": "{{.StartTime}}", "to": "{{.EndTime}}" },
 "panels": [
  {
   "title": "Working hours per day",
   "type": "graph",
   "description": "Total working hours per day",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select $__timeGroup(start::date, $__interval) as time,\n  sum(duration) as value,\n  'value' as series\n  from toggl_time\n  where $__timeFilter(start::date)\n  group by $__timeGroup(start::date, $__interval)\n  order by $__timeGroup(start::date, $__interval) asc"
    },
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Working hours per day per customer",
   "type": "graph",
   "description": "Working hours per day per customer",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select $__timeGroup(toggl_time.start::date, $__interval) as time,\n  sum(toggl_time.duration) as value,\n  trello_card.customer\nfrom toggl_time, trello_card\nwhere $__timeFilter(toggl_time.start::date) and toggl_time.trello_card_id = trello_card.id\ngroup by trello_card.customer, $__timeGroup(toggl_time.start::date, $__interval)\norder by $__timeGroup(toggl_time.start::date, $__interval) asc\n\n"
    }
   ]
  },
  {
   "title": "Working hours per customer",
   "type": "grafana-piechart-panel",
   "description": "Working hours per customer",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\n  now() as time,\n  sum(toggl_time.duration) as value,\n  trello_card.customer\nfrom toggl_time, trello_card\nwhere toggl_time.trello_card_id = trello_card.id\ngroup by trello_card.customer\n"
    }
   ]
  },
  {
   "title": "Working hours per day per type",
   "type": "graph",
   "description": "Working hours per day per type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select $__timeGroup(toggl_time.start::date, $__interval) as time,\n  sum(toggl_time.duration) as value,\n  trello_card.type\nfrom toggl_time, trello_card\nwhere $__timeFilter(toggl_time.start::date) and toggl_time.trello_card_id = trello_card.id\ngroup by trello_card.type, $__timeGroup(toggl_time.start::date, $__interval)\norder by $__timeGroup(toggl_time.start::date, $__interval) asc\n\n"
    }
   ]
  },
  {
   "title": "Count of stories per customer",
   "type": "table-old",
   "description": "Count of stories per customer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT customer, count(*)\nFROM trello_card\nGROUP BY customer;"
    }
   ]
  },
  {
   "title": "Count of stories per type",
   "type": "table-old",
   "description": "Count of stories per type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT type, count(*)\nFROM trello_card\nGROUP BY type;"
    }
   ]
  },
  {
   "title": "Working hours per customer per month",
   "type": "graph",
   "description": "Working hours per customer per month",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "Select \n  DATE_TRUNC('month', toggl_time.start::date) AS time,\n  sum(toggl_time.duration) as value,\n  trello_card.customer\nfrom toggl_time, trello_card\nwhere toggl_time.trello_card_id = trello_card.id\ngroup by trello_card.customer, DATE_TRUNC('month', toggl_time.start::date)\norder by DATE_TRUNC('month', toggl_time.start::date) asc\n"
    }
   ]
  },
  {
   "title": "Working hours per type per month",
   "type": "graph",
   "description": "Working hours per type per month",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "Select \n  DATE_TRUNC('month', toggl_time.start::date) AS time,\n  sum(toggl_time.duration) as value,\n  trello_card.type\nfrom toggl_time, trello_card\nwhere toggl_time.trello_card_id = trello_card.id\ngroup by trello_card.type, DATE_TRUNC('month', toggl_time.start::date)\norder by DATE_TRUNC('month', toggl_time.start::date) asc\n"
    }
   ]
  },
  {
   "title": "Working hours per customer per month (percentage)",
   "type": "graph",
   "description": "Working hours per customer per month (percentage)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Working hours per type per month (percentage)",
   "type": "graph",
   "description": "Working hours per type per month (percentage)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Count of stories per customer per month",
   "type": "graph",
   "description": "Count of stories per customer per month",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "Select \n  DATE_TRUNC('month', toggl_time.start::date) AS time,\n  count(*),\n  trello_card.customer\nfrom toggl_time, trello_card\nwhere toggl_time.trello_card_id = trello_card.id\ngroup by trello_card.customer, DATE_TRUNC('month', toggl_time.start::date)\norder by DATE_TRUNC('month', toggl_time.start::date) asc"
    }
   ]
  },
  {
   "title": "Count of stories per type per month",
   "type": "graph",
   "description": "Count of stories per type per month",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "Select \n  DATE_TRUNC('month', toggl_time.start::date) AS time,\n  count(*),\n  trello_card.type\nfrom toggl_time, trello_card\nwhere toggl_time.trello_card_id = trello_card.id\ngroup by trello_card.type, DATE_TRUNC('month', toggl_time.start::date)\norder by DATE_TRUNC('month', toggl_time.start::date) asc"
    }
   ]
  }
 ]
}