APPLICATION_LOG_LEVEL: "error"
TOGGL_API_TOKEN: ""
TRELLO_APP_KEY: ""
TRELLO_API_TOKEN: ""
TRELLO_BOARD_ID: ""
TRELLO_LABEL_PROJECT_COLOR: ["sky"]
TRELLO_LABEL_CUSTOMER_COLOR: ["green"]
TRELLO_LABEL_TEAM_COLOR: ["yellow"]
TRELLO_LABEL_CARD_TYPE_COLOR: ["red", "blue"]
DATABASE_HOST: "127.0.0.1"
DATABASE_PORT: "5432"
DATABASE_NAME: "toggltrelloapi"
DATABASE_USERNAME: "postgres"
DATABASE_PASSWORD: "postgres"
DATABASE_MAX_OPEN_CONNECTIONS: 80
DATABASE_MAX_IDLE_CONNECTIONS: 40
DATABASE_MAX_LIFETIME_IN_MINUTES: 60
GRAFANA_YEAR: "2021"
GRAFANA_START_MONTH: "02"
GRAFANA_END_MONTH: "08"